name: publish

on: [push]

jobs:
  build:
    name: GCR Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest
            - name: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        id: helloworld
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: helloworld
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:latest
          region: eu-north1

      - name: Show Output
        run: echo ${{ steps.helloworld.outputs.url }}
